export const SCAN_OPTIONS = {
  frequency: ['Nunca', 'Raramente', 'Às vezes', 'Frequentemente', 'Sempre'],
  frequencyReversed: ['Sempre', 'Frequentemente', 'Às vezes', 'Raramente', 'Nunca'],
  coherence: ['Muito baixa', 'Baixa', 'Moderada', 'Alta', 'Muito alta'],
  balance: ['Muito baixo', 'Baixo', 'Moderado', 'Alto', 'Muito alto'],
  adequacy: ['Muito inadequados', 'Inadequados', 'Moderados', 'Adequados', 'Muito adequados'],
  priorityClarity: ['Muito baixas', 'Baixas', 'Moderadas', 'Altas', 'Muito altas'],
  decisionImpact: ['Enfraquecem muito', 'Enfraquecem', 'Neutras', 'Apoiam', 'Apoiam fortemente'],
  barriers: ['Extremamente altas', 'Altas', 'Moderadas', 'Baixas', 'Muito baixas'],
  amount: ['Muito pouco', 'Pouco', 'Moderadamente', 'Muito', 'Totalmente'],
  speed: ['Muito lentamente', 'Lentamente', 'Moderadamente', 'Rapidamente', 'Muito rapidamente'],
  fear: ['Muito alto', 'Alto', 'Moderado', 'Baixo', 'Muito baixo'],
  silos: ['Muito fortes', 'Fortes', 'Moderados', 'Fracos', 'Inexistentes'],
  quality: ['Muito mal', 'Mal', 'Razoavelmente', 'Bem', 'Muito bem'],
  nps: ['Definitivamente não', 'Provavelmente não', 'Talvez', 'Provavelmente sim', 'Definitivamente sim'],
  npsExtended: [
    'Definitivamente não',
    'Provavelmente não',
    'Parcialmente',
    'Provavelmente sim',
    'Definitivamente sim',
  ],
  journeyMap: ['Não existe', 'Parcialmente', 'Básica', 'Bem definida', 'Totalmente integrada'],
  processImpact: ['Dificultam muito', 'Dificultam', 'Neutros', 'Facilitam', 'Facilitam muito'],
  maturity: ['Inexistente', 'Inicial', 'Parcial', 'Estruturado', 'Altamente maduro'],
  onboarding: ['Muito pouco', 'Pouco', 'Moderadamente', 'Muito', 'Extremamente'],
  evolution: ['Piorou muito', 'Piorou', 'Permaneceu igual', 'Melhorou', 'Melhorou muito'],
  turnoverCompare: ['Muito abaixo', 'Abaixo', 'Similar', 'Acima', 'Muito acima'],
  turnoverGroups: [
    'Novos contratados',
    'Operação',
    'Liderança',
    'Alta performance',
    'Jovens talentos',
    'Especialistas',
    'Profissionais experientes',
    'Outros',
  ],
  tenure: ['Menos de 90 dias', '3 a 6 meses', '6 a 12 meses', '1 a 3 anos', 'Mais de 3 anos'],
  onboardingFeeling: ['Entusiasmo', 'Clareza', 'Confusão', 'Sobrecarga', 'Indiferença'],
  leadershipStyle: [
    'Desenvolve pessoas',
    'Entrega resultados',
    'Resolve problemas',
    'Controla excessivamente',
    'Apaga incêndios',
  ],
  riskPercent: ['Menos de 10%', '10–20%', '20–30%', '30–40%', 'Acima de 40%'],
  stayReasons: [
    'Crescimento',
    'Líder',
    'Flexibilidade',
    'Cultura',
    'Reconhecimento',
    'Salário',
    'Aprendizagem',
    'Propósito',
  ],
  leaveReasons: [
    'Falta de crescimento',
    'Liderança',
    'Sobrecarga',
    'Cultura',
    'Salário',
    'Benefícios',
    'Falta de reconhecimento',
    'Falta de propósito',
  ],
  turnoverCauses: [
    'Liderança',
    'Salário',
    'Carreira',
    'Cultura',
    'Sobrecarga',
    'Benefícios',
    'Flexibilidade',
    'Ambiente',
    'Falta de reconhecimento',
  ],
} as const;
