import type { OrganizationalScanDefinition } from '../../types/organizationalScans';
import { customBlock } from './builders';
import { SCAN_OPTIONS as O } from './options';

export const turnoverScan: OrganizationalScanDefinition = {
  id: 'turnover',
  step: 'Scan 7',
  title: 'High Turnover Scan',
  subtitle: 'Causas, riscos e retenção de talentos',
  intro:
    'A rotatividade de colaboradores é frequentemente um sintoma de desafios mais profundos relacionados à liderança, cultura, experiência do colaborador ou condições de trabalho. Este diagnóstico identifica causas que influenciam a retenção e os impactos do turnover.',
  guidance:
    'Responda com base em dados, tendências e evidências observadas ao longo do tempo. Use entrevistas de desligamento, pesquisas internas e indicadores de pessoas sempre que possível.',
  blocks: [
    customBlock('turnover_problem', 'O turnover é realmente um problema?', [
      {
        id: 'turnover_voluntary_pct',
        prompt: 'Qual foi o turnover voluntário dos últimos 12 meses?',
        type: 'percent',
        required: true,
        placeholder: 'Ex.: 18',
      },
      {
        id: 'turnover_market_compare',
        prompt: 'Comparado ao mercado, este turnover é:',
        type: 'single',
        options: [...O.turnoverCompare],
        required: true,
      },
      {
        id: 'turnover_leadership_concern',
        prompt: 'Em uma escala de 0 a 10, quanto este turnover preocupa a liderança?',
        type: 'scale',
        min: 0,
        max: 10,
        required: true,
      },
      {
        id: 'turnover_situation_phrase',
        prompt: 'Se pudesse escolher apenas uma frase, qual melhor descreve a situação atual?',
        type: 'single',
        options: [
          'Perdemos poucas pessoas',
          'Perdemos muitas pessoas',
          'Perdemos as pessoas erradas',
          'Perdemos talentos críticos',
          'Não sabemos exatamente quem estamos perdendo',
        ],
        required: true,
      },
    ]),
    customBlock('turnover_who', 'Quem está saindo?', [
      {
        id: 'turnover_groups',
        prompt: 'Quais grupos apresentam maior rotatividade? Selecione até 3.',
        type: 'multi',
        options: [...O.turnoverGroups],
        maxSelections: 3,
        required: true,
      },
      {
        id: 'turnover_tenure',
        prompt: 'Quanto tempo, em média, os colaboradores permanecem antes de sair?',
        type: 'single',
        options: [...O.tenure],
        required: true,
      },
      {
        id: 'turnover_leave_when',
        prompt: 'Complete a frase: "As pessoas geralmente decidem sair quando..."',
        type: 'text',
        required: true,
        placeholder: 'Descreva o momento ou gatilho mais comum',
      },
    ]),
    customBlock('turnover_expectation', 'Expectativa vs realidade', [
      {
        id: 'turnover_promise_match',
        prompt: 'Quanto a experiência real corresponde ao que foi prometido no recrutamento?',
        type: 'scale',
        min: 0,
        max: 10,
        required: true,
      },
      {
        id: 'turnover_disappointment',
        prompt: 'Qual destes itens mais decepciona novos colaboradores? Escolha até 3.',
        type: 'multi',
        options: [
          'Liderança',
          'Cultura',
          'Carreira',
          'Salário',
          'Benefícios',
          'Ambiente',
          'Volume de trabalho',
          'Desenvolvimento',
          'Flexibilidade',
        ],
        maxSelections: 3,
        required: true,
      },
      {
        id: 'turnover_first_90_score',
        prompt: 'Se um colaborador recém-contratado pudesse dar uma nota para seus primeiros 90 dias, qual seria?',
        type: 'scale',
        min: 0,
        max: 10,
        required: true,
      },
      {
        id: 'turnover_onboarding_feeling',
        prompt: 'O onboarding hoje gera:',
        type: 'single',
        options: [...O.onboardingFeeling],
        required: true,
      },
    ]),
    customBlock('turnover_causes', 'Investigação das causas', [
      {
        id: 'turnover_distribution',
        prompt: 'Distribua 100 pontos entre os fatores abaixo de acordo com sua influência no turnover.',
        type: 'distribution',
        options: [...O.turnoverCauses],
        distributionTotal: 100,
        required: true,
      },
      {
        id: 'turnover_underestimated',
        prompt: 'Qual fator você acredita ser mais subestimado pela organização?',
        type: 'text',
        required: true,
      },
      {
        id: 'turnover_exit_reasons_known',
        prompt: 'A empresa conhece as verdadeiras razões dos desligamentos?',
        type: 'scale',
        min: 0,
        max: 10,
        required: true,
      },
    ]),
    customBlock('turnover_leadership', 'Liderança como causa ou solução', [
      {
        id: 'turnover_leadership_retain',
        prompt: 'Quanto a liderança contribui para reter talentos?',
        type: 'scale',
        min: 0,
        max: 10,
        required: true,
      },
      {
        id: 'turnover_leadership_cause_prob',
        prompt: 'Se uma pessoa decide sair, qual a probabilidade de a liderança ser parte da causa?',
        type: 'scale',
        min: 0,
        max: 10,
        required: true,
      },
      {
        id: 'turnover_leader_exit_observed',
        prompt: 'Você já observou colaboradores saindo por causa de um líder específico?',
        type: 'single',
        options: ['Nunca', 'Raramente', 'Algumas vezes', 'Frequentemente', 'Muitas vezes'],
        required: true,
      },
      {
        id: 'turnover_leadership_style',
        prompt: 'Qual frase melhor descreve a liderança atual?',
        type: 'single',
        options: [...O.leadershipStyle],
        required: true,
      },
    ]),
    customBlock('turnover_risk', 'Risco de saída futura', [
      {
        id: 'turnover_top_talent_tendency',
        prompt: 'Seus melhores talentos estão mais propensos a:',
        type: 'single',
        options: ['Permanecer', 'Considerar propostas', 'Buscar ativamente oportunidades', 'Não sabemos'],
        required: true,
      },
      {
        id: 'turnover_risk_percent',
        prompt: 'Qual percentual da equipe você considera em risco de saída nos próximos 12 meses?',
        type: 'single',
        options: [...O.riskPercent],
        required: true,
      },
      {
        id: 'turnover_competitor_poach',
        prompt: 'Se um concorrente oferecesse 15% a mais, quantos dos seus melhores talentos sairiam?',
        type: 'scale',
        min: 0,
        max: 10,
        required: true,
      },
    ]),
    customBlock('turnover_retention', 'Teste de retenção', [
      {
        id: 'turnover_stay_probability',
        prompt:
          'Imagine que você é um colaborador de alta performance desta organização. Qual a probabilidade de permanecer pelos próximos 2 anos?',
        type: 'scale',
        min: 0,
        max: 10,
        required: true,
      },
      {
        id: 'turnover_stay_reasons',
        prompt: 'O que mais faria você permanecer? Escolha até 3.',
        type: 'multi',
        options: [...O.stayReasons],
        maxSelections: 3,
        required: true,
      },
      {
        id: 'turnover_leave_reasons',
        prompt: 'O que mais faria você sair? Escolha até 3.',
        type: 'multi',
        options: [...O.leaveReasons],
        maxSelections: 3,
        required: true,
      },
      {
        id: 'turnover_one_fix',
        prompt: 'Se pudesse resolver apenas UMA causa do turnover amanhã, qual seria?',
        type: 'text',
        required: true,
      },
    ]),
  ],
};
